enum Errors {
  OEMBED_ADAPTER_NOT_FOUND = 'OEMBED_ADAPTER_NOT_FOUND',
  OEMBED_URL_NOT_FOUND = 'OEMBED_URL_NOT_FOUND',
  E_DATA_VALIDATION_FAILED = 'E_DATA_VALIDATION_FAILED',
  E_CANNOT_FIND_DOCUMENT = 'E_CANNOT_FIND_DOCUMENT',
}

export default Errors;
