version: "3"
services:
  mongodb:
    restart: always
    image: mongo:latest
    container_name: mongodb
    hostname: mongodb
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: klaxoon
      MONGO_INITDB_ROOT_PASSWORD: "555HvysMDMXux2E6"
  api:
    restart: always
    image: node:lts-slim
    build:
      context: .
      dockerfile: deployment/local/Dockerfile
    container_name: technical-test-api
    hostname: api
    ports:
      - 8080:8080
    environment:
      PORT: 8080
      MONGO_HOST: "mongodb:27017"
      MONGO_ADDRESS: "mongodb:27017"
      MONGO_DATABASE: even
      MONGO_USER: klaxoon
      MONGO_PASSWORD: "555HvysMDMXux2E6"
      NODE_ENV: production
      URL: "http://localhost:8080/"
    links:
      - mongodb
    depends_on:
      - mongodb

